[credentials]
USER     = "Demosthenis"
PASSWORD = "2024InvoiceTest%1"

[client]
showSidebarNavigation = false

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ypFEY-zuk9Eek85P_C4j4nsF7T-_3Wva_WVZB7oXjmg/edit#grid=2090513002"

# From your JSON key file
type= "service_account"
project_id= "causal-scarab-447116-s1"
private_key_id= "be2eb21905baa2c425ce9a8869756dded27dd059"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtfQCoI5Zmp6mv\n702ZD8rxtDxM4acTe+gFslZSOOE0apNyb8Sd7k23LDhUSuzLX9bWY4IEJOa663kW\nBJAzrLiF6nV3v1sHjQwlGvo5R0IECniuvZ+tRnxbUCq6Aig0ON5Kvt50oWBoCd4B\nusHZ+qxFOPxgjXsbSNGvvFKyW5M2jPp26v70+d8goo7HCmY4Qu+YzKuc+DH8wenk\nIDXAGfrVWnhhCBGbIzm+nr5vZCV2bnBcP6wUOzdyGlD8dZVgA8m6BLGrgp47YXLn\nUTijVixb1+GXw3vOChXiQ51wFoDzITT7pkgNs7l78ieRPj1hvyLKOPJlad9pAWL7\nw1jQKGLJAgMBAAECggEAAuA5kIbT7OV/1RIJNykoQIuv3BFnZXEuauvB21n/9Wu7\nSVmHdncuOLGl/9Nt/fXJXKyD9476ClIfvzIVYkwx3CfeyWp+0o74wfX+M9DMsKys\nMR0Sz6hp//bLIoa7svPqzyR2NaY8wmubvTSHcp9qswIP7mKGl5U7MOfVCPeCJvkR\nggljn7KRWqHkOWgDV+ZQ7P2EFnJCBmIt8YH30cvO5TVkK8IUd8GVfKDAAn19+zLX\naCu5fTZkYqMj025uhglpCh1NK61jaotCBjLs8fihpY9+Gp8x30ySTudrcwunQ6k1\njBDjliSgWZYtwwwHQfIX6ofPijNsROEMBNdAQ7zHhQKBgQDjD9TBz4TJWlkyYkgs\nd/jxWi+fCiJ23Ohxso3Drmu+3UMYFXSU0MhBhUxQn3dUYLrYU43LuypTY6Ux1C1D\n7DWfMz2J5Cld2aR1yNIAetQvRZEKyZHAEGRE545A6RUpGmObLvTL9dII4H/7gtJI\nDbuFtFBh+yHKndo2steYfulzJQKBgQDDmUTs7oqO9PYrwYDz6YXC252LSmcjK1Bq\nwpA48p8ZgKMoPpcg9ldG2EYvaVG8u4apj6ldLWhXcEBhVKyLRrqmFNCqVoEUB5kF\nOazKY98dgGJE+7h64bj+8ZluKIFd7tR1o7CU/PFnX4+UMvZGnTDdPl5eX0QBs+Se\no8xgqGOx1QKBgQDiOE2SYrw7F8aySfT6SPU/EMlNPH2lyuXTET/oa4hxemR0RDwI\nYBKEJNgpoxbyfATrriMhjXHX7vkQsgH/IAE0gYqYLTeBh2sw5klDrRxllHuzMawC\nnNIpTEIQLailcOM4IwpFgr4llfYskOQMYZIo3cMQO3IpOifEQ15FUnwn+QKBgAWt\nNxDhQ2gut85BSWrKxjUHhqT6PdAJe8X9a44bjH6C+zk5x80PGS1XLYJGvjaKArh9\nEN9BaBvRiCzK9k78eIJFbGDlLc3VAp3iNJ+TEnCavz9dRtdaIbJUdK17w3VkbwoS\n/Bb22FK1tUcJy5f1C+v/2WFHxoN+Iw5vlojfmjUZAoGBAMzA1PYzpHJa/+ptkDCE\nDxz+sorYK8GL9zf1cP4s7PSD+UzgXM7m/V2vDuSmRvdYMX0fDX0rtR+vY77VQR4o\n/Ll03G9YyCCRWgYvacItlotZnhyB1/VHCdophA22hg1WZWmqyuVmSGFcGBdRGJDY\nfanpy30tEaAoG6/gpSwfOkTS\n-----END PRIVATE KEY-----\n"
client_email= "dd-viewer@causal-scarab-447116-s1.iam.gserviceaccount.com"
client_id= "104416802373609741899"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/dd-viewer%40causal-scarab-447116-s1.iam.gserviceaccount.com"
universe_domain= "googleapis.com"
